name: CI para projeto simples

on:
  push:
    branches: [ main, desenvolvimento ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Verificar presença do index.html
      run: |
        if [ -f index.html ]; then
          echo "index.html encontrado!"
        else
          echo "index.html não encontrado!"
          exit 1
        fi
